{
 "title": "Custom Exporter Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Распределение по рангам",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "valorant_players_by_rank", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Использование оружия",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "valorant_weapon_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Использование способностей",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(valorant_ability_used_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Матчи по режимам",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (mode) (increase(valorant_matches_played_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Курсы валют",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "external_currency_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Процент хедшотов ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "valorant_headshot_percentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Температура погоды ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "external_weather_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Задержка сервера",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "valorant_server_latency_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "K/D ratio (среднее за 5 мин)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "avg_over_time(valorant_kill_death_ratio[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Онлайн игроки Valorant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    { "expr": "valorant_players_online", "legendFormat": "__auto" }
   ]
  }
 ]
}