{
 "title": "Node Exporter Dashboard ",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Курсы валют",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "external_currency_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Температура",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "external_weather_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Матчи по режимам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (mode) (increase(valorant_matches_played_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K/D ratio (среднее за 5 мин)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg_over_time(valorant_kill_death_ratio[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Онлайн игроки Valorant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "valorant_players_online", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Распределение нагрузки CPU",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk I/O по устройствам",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$instance\"}[5m]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сетевой трафик",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$instance\"}[5m]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Общая память",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время работы системы",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds{instance=~\"$instance\"} - node_boot_time_seconds{instance=~\"$instance\"}) / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество процессов",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_procs_running{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Свободное место на диске",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$instance\", mountpoint=~\"/.*\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{instance=~\"$instance\"} / node_memory_MemTotal_bytes{instance=~\"$instance\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Загрузка CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "# Загрузка CPU в %\r\n100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "# Использование памяти %\r\n(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "# Свободное место на диске (GB)\r\nnode_filesystem_avail_bytes{mountpoint=\"/\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}